[package]
name = "rs-sync"
version = "0.1.0"
edition = "2021"
authors = ["Vladimir Pinchuk"]

[dependencies]
libm = "0.2.2"
argmin = { version = "0.7.0", default-features = false }
argmin-math = "0.2.0"
superslice = "1.0.0"
nalgebra = "0.30"
rayon = "1.5.3"
rand = "0.8.5"
log = "0.4.17"